language: elixir

elixir:
  - 1.8

otp_release:
  - 20.3
  - 21.0

script:
  - mix deps.get
  - mix format --check-formatted
  - mix test
  - MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)
